### ISSUE TITLE
Install hadley/productplots before ggobi/cranvas

### ISSUE THREAD

**Issue by cpsievert** [ggobi/cranvas#214]
After following the [installation directions for Mac](http://cranvas.org/download.html#install-qt-under-mac-os-x), I did:

```
install_github("ggobi/cranvas")
```

which gave me:

```
ERROR: dependency ‘productplots’ is not available for package ‘cranvas’
```

So you may want to change

```
install_github(c('ggobi/qtbase', 'ggobi/qtpaint'))
```

to

```
install_github(c('ggobi/qtbase', 'ggobi/qtpaint', "hadley/productplots"))
```

**Comment by chxy** [comment]
You also have to install several other packages in the first chunk of that page. The [installation directions for Mac](http://cranvas.org/download.html#install-qt-under-mac-os-x) is actually only for installing *Qt*, the *cranvas* part is at the beginning.

**Comment by cpsievert** [comment]
Ooops, sorry, I skipped over that part. Good news is I was able to finally able install cranvas without error!

![celebrate](https://cloud.githubusercontent.com/assets/1365941/6198537/879074de-b3cd-11e4-9e72-109859f28dbd.gif)
